# Generated by Django 5.2.4 on 2025-07-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forSale', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xpos', models.IntegerField()),
                ('Ypos', models.IntegerField()),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.gallery')),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.painting')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='paintings',
            field=models.ManyToManyField(through='ArtDatabase.GalleryPainting', to='ArtDatabase.painting'),
        ),
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ArtDatabase.painting')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('paintings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.painting')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paintings',
            field=models.ManyToManyField(through='ArtDatabase.PortfolioPainting', to='ArtDatabase.painting'),
        ),
        migrations.AddConstraint(
            model_name='gallerypainting',
            constraint=models.UniqueConstraint(fields=('painting', 'gallery'), name='unique_gallery_painting'),
        ),
        migrations.AddConstraint(
            model_name='portfoliopainting',
            constraint=models.UniqueConstraint(fields=('paintings', 'portfolio'), name='unique_portfolio_painting'),
        ),
    ]
