# Generated by Django 5.2.4 on 2025-07-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='forSale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
