# Generated by Django 5.2.4 on 2025-07-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(choices=[('PU', 'pickup'), ('SD', 'standard')], max_length=2),
        ),
    ]
