# Generated by Django 5.2.4 on 2025-07-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0002_painting_forsale_painting_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
