# Generated by Django 5.2.4 on 2025-07-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0002_alter_purchaseorder_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
