# Generated by Django 5.2.4 on 2025-07-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0003_alter_purchaseorder_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date_ordered',
            new_name='date_purchased',
        ),
    ]
