# Generated by Django 5.2.4 on 2025-07-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0003_painting_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xpos', models.IntegerField()),
                ('Ypos', models.IntegerField()),
                ('galleries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtDatabase.gallery')),
                ('paintings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtDatabase.painting')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='paintings',
            field=models.ManyToManyField(through='ArtDatabase.GalleryPainting', to='ArtDatabase.painting'),
        ),
        migrations.CreateModel(
            name='PortfolioPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('paintings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtDatabase.painting')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtDatabase.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='gallerypainting',
            constraint=models.UniqueConstraint(fields=('paintings', 'galleries'), name='unique_gallery_painting'),
        ),
        migrations.AddConstraint(
            model_name='portfoliopainting',
            constraint=models.UniqueConstraint(fields=('paintings', 'portfolio'), name='unique_portfolio_painting'),
        ),
    ]
