# Generated by Django 5.2.4 on 2025-07-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0004_rename_date_ordered_purchaseorder_date_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date_purchased',
            new_name='date_ordered',
        ),
    ]
