# Generated by Django 5.2.4 on 2025-07-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0004_gallery_portfolio_gallerypainting_gallery_paintings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paintings',
            field=models.ManyToManyField(through='ArtDatabase.PortfolioPainting', to='ArtDatabase.painting'),
        ),
        migrations.AlterField(
            model_name='gallerypainting',
            name='galleries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.gallery'),
        ),
        migrations.AlterField(
            model_name='gallerypainting',
            name='paintings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.painting'),
        ),
        migrations.AlterField(
            model_name='portfoliopainting',
            name='paintings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.painting'),
        ),
        migrations.AlterField(
            model_name='portfoliopainting',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtDatabase.portfolio'),
        ),
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ArtDatabase.painting')),
            ],
        ),
    ]
