# Generated by Django 5.2.4 on 2025-07-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0005_rename_date_purchased_purchaseorder_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
