# Generated by Django 5.2.4 on 2025-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtDatabase', '0005_remove_painting_images_portfolio_paintings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingimage',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
